// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/eventhq-client-login/ClientLogin.tsx": () => import("../components/mockups/eventhq-client-login/ClientLogin.tsx"),
  "./components/mockups/eventhq-sidebar/Current.tsx": () => import("../components/mockups/eventhq-sidebar/Current.tsx"),
  "./components/mockups/eventhq-sidebar/Refined.tsx": () => import("../components/mockups/eventhq-sidebar/Refined.tsx"),
  "./components/mockups/eventhq-training/Current.tsx": () => import("../components/mockups/eventhq-training/Current.tsx"),
  "./components/mockups/eventhq-training/Refined.tsx": () => import("../components/mockups/eventhq-training/Refined.tsx")
};
